name: Terraform Workflow

on:
  push:
    branches:
      - main  # Adjust branch as needed

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan
      
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Change conditions as needed
      run: terraform apply -auto-approve tfplan
      
    - name: Terraform Validate
      run: terraform validate   
      
    - name: Terraform Destroy
      if: github.event_name == 'pull_request'  # Adjust conditions as needed
      run: terraform destroy -auto-approve
